In [15]:
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np

from keras.preprocessing import image
model = load_model('facefeatures_new_models.h5')

# Loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)/255
        img_array = np.expand_dims(img_array, axis=0)
        pred=model.predict(img_array)
        print(pred)
        if(pred[0][0]>=0.65):
            cv2.putText(frame,'Himanshu', (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
        elif(pred[0][1]>=0.65):
            cv2.putText(frame,'kohli', (100, 100), cv2.FONT_HERSHEY_COMPLEX, 2, (0,255,255), 2)
        else:
            cv2.putText(frame,'None', (100, 100), cv2.FONT_HERSHEY_COMPLEX, 2, (0,255,0), 2)
            
            
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

<>:24: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:24: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-15-9258e527484b>:24: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


[[0.9627388  0.03726114]]
[[0.89249825 0.10750179]]
[[0.9338928  0.06610721]]
[[0.87194395 0.12805603]]
[[0.9075833  0.09241676]]
[[0.8167343  0.18326563]]
[[0.74636316 0.2536368 ]]
[[0.93194234 0.06805768]]
[[0.8322652  0.16773479]]
[[0.89769906 0.10230094]]
[[0.93607163 0.0639283 ]]
[[0.9232378  0.07676216]]
[[0.9214011  0.07859886]]
[[0.91090125 0.0890988 ]]
[[0.88455534 0.11544467]]
[[0.9157458  0.08425415]]
[[0.92749226 0.07250781]]
[[0.9457747  0.05422536]]
[[0.9474571  0.05254291]]
[[0.9728047  0.02719522]]
[[0.9823192  0.01768087]]
[[0.9849235  0.01507655]]
[[0.9744324  0.02556759]]
[[0.9863376  0.01366239]]
[[0.98630327 0.0136967 ]]
[[0.9617631  0.03823697]]
[[0.94997853 0.05002148]]
[[0.9697701 0.03023  ]]
[[0.9737714  0.02622862]]
[[0.96554685 0.03445316]]
[[0.98078376 0.01921627]]
[[0.44803092 0.5519691 ]]
[[0.98663354 0.0133664 ]]
[[0.9791919  0.02080808]]
[[0.97586626 0.02413376]]
[[0.94721144 0.05278858]]
